### ISSUE TITLE
Submodules not pinned to version. Mismatch between aws-c-io and vcpkg

### ISSUE THREAD

**Issue by jwielebnowski** [awslabs/aws-crt-cpp#105]
On Feb 4th there was a dependency introduced in the aws-c-io. Anything after tag/v.0.7.3 (Jan 29th) it pulls that dependency from Feb 4th and since vcpkg core is not in sync cmake breaks with 

C:\projects-2020\deps\include\aws\io\io.h(100): error C3861: 'AWS_ERROR_ENUM_BEGIN_RANGE': identifier not found 

where error.h file comes from -IC:\projects-2020\vcpkg\installed\x64-windows\include

Please confirm.

**Comment by rccarper** [comment]
Hello!  It sounds like you may have a conflicting setup, where your project is pointing to vcpkg's aws-c-common, but to the submodules for other libraries, such as aws-c-io.  Is that possible?

If you are making use of the submodules in aws-crt-cpp, you shouldn't have to rely on anything else (in this case, vcpkg) to pull in aws-c-common--it's already itself a submodule.
