### ISSUE TITLE
UUID::ToString() always returns an empty string

### ISSUE THREAD

**Issue by TripleWhy** [awslabs/aws-crt-cpp#116]
I was wondering why my strings in one of the aws samples were empty and looked into UUID::ToString(). It seems like the data is written do the buffer of the returned string, but the string is never informed that its length is not 0 anymore:

```c++
        String UUID::ToString() const
        {
            String uuidStr;
            uuidStr.reserve(AWS_UUID_STR_LEN);

            auto outBuf = ByteBufFromEmptyArray(reinterpret_cast<const uint8_t *>(uuidStr.data()), uuidStr.capacity());
            aws_uuid_to_str(&m_uuid, &outBuf);
            return uuidStr;
        }
```

**Comment by TingDaoK** [comment]
Hi, Thank you for reaching out and reporting the bug to us. The fix is here https://github.com/awslabs/aws-crt-cpp/pull/118 and it's merged into master! Thank you!
