### ISSUE TITLE
base64 encode logic is not right in Types.cpp

### ISSUE THREAD

**Issue by goingeast** [awslabs/aws-crt-cpp#122]
if (aws_base64_encode(&toEncode, &tempBuf))
{
     return output;
}

should be

if (aws_base64_encode(&toEncode, &tempBuf) != AWS_OP_SUCCESS)
{
     return output;
}

**Comment by justinboswell** [comment]
```AWS_OP_SUCCESS``` is 0, so the logic is correct either way. Most of our C codebase uses the same pattern.

**Comment by goingeast** [comment]
Sorry, It is my typo. it should be equal. as you mentioned  AWS_OP_SUCCESS is 0. so in your original code, AWS_OP_SUCCESS will not return the result.

if (aws_base64_encode(&toEncode, &tempBuf) **==** AWS_OP_SUCCESS)
{
return output;
}

**Comment by justinboswell** [comment]
Ha, good catch, I've opened a PR with the fix, thanks!

**Comment by justinboswell** [comment]
PR is merged, along with an additional bug fix for that encoding API. Thanks for the report!
