### ISSUE TITLE
Wrong version number

### ISSUE THREAD

**Issue by kankri** [awslabs/aws-crt-cpp#124]
The [version number](../blob/v0.8.4/CMakeLists.txt#L36) which is included in the [MQTT connection information](../blob/v0.8.4/source/iot/MqttClient.cpp#L350) is wrong.

It seems the version number has been correct in 7 releases out of 36 and incorrect in the rest 29 releases:

| release tag | version number |
| ----------- | -------------- |
|      v0.3.1 |         v0.3.0 |
|      v0.3.2 |         v0.3.0 |
|      v0.4.0 |         v0.3.0 |
|      v0.4.1 |         v0.3.0 |
|      v0.4.2 |         v0.3.0 |
|      v0.4.4 |         v0.3.0 |
|      v0.4.5 |         v0.3.0 |
|      v0.4.6 |         v0.3.0 |
|      v0.5.0 |         v0.3.0 |
|      v0.5.1 |         v0.3.0 |
|      v0.5.2 |         v0.3.0 |
|      v0.5.3 |         v0.3.0 |
|      v0.5.4 |         v0.3.0 |
|      v0.5.5 |         v0.3.0 |
|      v0.6.0 |         v0.5.6 |
|      v0.6.1 |         v0.5.6 |
|      v0.6.3 |         v0.6.2 |
|      v0.6.4 |         v0.6.2 |
|      v0.6.6 |         v0.6.5 |
|      v0.6.7 |         v0.6.5 |
|      v0.6.9 |         v0.6.8 |
|     v0.6.10 |         v0.6.8 |
|      v0.7.2 |         v0.7.1 |
|      v0.7.4 |         v0.7.3 |
|      v0.7.5 |         v0.7.3 |
|      v0.7.6 |         v0.7.3 |
|      v0.8.1 |         v0.7.3 |
|      v0.8.3 |         v0.8.2 |
|      v0.8.4 |         v0.8.2 |

Maybe the version number should be generated automatically?

**Comment by justinboswell** [comment]
Good catch! This should be overwritten by our release process, but isn't currently. Will fix.
