### ISSUE TITLE
Git version history and tag problem

### ISSUE THREAD

**Issue by kankri** [awslabs/aws-crt-cpp#143]
I mentioned this in https://github.com/awslabs/aws-c-mqtt/issues/135#issuecomment-648236162, but thought to create an issue to the repository which is affected.

It seems to me that existing tags v0.8.4 and v0.8.5 have been changed to point to different commits recently. My previous clone shows:

```
* commit 393433e9fcfe48ab09c02a23577724f96dcdee5f (HEAD, tag: v0.8.5)
| Author: Bret Ambrose <bretambrose@gmail.com>
| Date:   Mon Jun 15 11:31:40 2020 -0700
```

```
* commit 421a69a81fb73b4c9917ffb3d095c2c65e9e973d (tag: v0.8.4)
| Author: Justin Boswell <boswej@amazon.com>
| Date:   Mon Jun 8 15:02:10 2020 -0700
```

My current clone shows:

```
* commit 107f24676a9f99bc5c5e61abe61b69044117c8fe (tag: v0.8.4)
| Author: GitHub Actions <aws-sdk-common-runtime@amazon.com>
| Date:   Tue Jun 23 01:55:40 2020 +0000
|
|     Updated version to v0.8.4
|
* commit 8c45c499e10eb2ea49fa56698c156e9bb9583f4c (origin/update_dep)
| Author: Dengke Tang <dengket@amazon.com>
| Date:   Mon Jun 22 18:55:15 2020 -0700
* commit fb751d0ea75401423c07acd4737fd0b7a7fc2bdc (origin/master, origin/HEAD, master)
| Author: Justin Boswell <boswej@amazon.com>
| Date:   Thu Jun 18 09:09:15 2020 -0700
| * commit 31fd668ef26af0ae0ee1ee84c01f7466b023e67f (tag: v0.8.5)
| | Author: GitHub Actions <aws-sdk-common-runtime@amazon.com>
| | Date:   Wed Jun 17 23:34:12 2020 +0000
| |
| |     Updated version to v0.8.5
| |
| * commit c2dfd35805f25e28ec933a29e3a2bf77a22e5afa
|/  Author: Justin Boswell <boswej@amazon.com>
|   Date:   Wed Jun 17 23:33:37 2020 +0000
* commit 9fda1e3309a4de37c2f052c5b1d531537c70b8a3
```

The new tags don't look reasonable and existing tags shouldn't be reassigned in any case. Is this some automation running amok?

**Comment by bretambrose** [comment]
I'm not sure it's the whole issue, but I may have screwed things up by forgetting to mark 0.8.5 as a pre-release.

**Comment by kankri** [comment]
What's the status of this, how soon can you restore the tags? We are currently using v0.8.4 in our automation and have had to prevent any attempts to pull that from GitHub and clone it locally instead.

**Comment by TingDaoK** [comment]
I am not sure about it either, but the new version, v0.8.6, has been released. You can try again and see if the issue is still there.

**Comment by kankri** [comment]
Thanks for the comment. There is indeed version v0.8.6 available, but tags v0.8.5 and v0.8.4 are still pointing to wrong commits as I wrote above. I hope that gets fixed soon.

**Comment by kankri** [comment]
I noticed also tags v0.8.2 and v0.8.3 are broken, when I was looking at [changes between v0.7.5 and v0.8.3](https://github.com/awslabs/aws-crt-cpp/compare/v0.7.5...v0.8.3) and noticing some suspiciously new commits in that list.

The tags should be:
```
* commit e84c3402ee0a1d00d5d66a0a8e803f33a64fccb4 (tag: v0.8.2)
| Author: Jonathan M. Henson <henso@amazon.com>
| Date:   Fri Mar 27 12:22:03 2020 -0700
|
|     Forgot to update the version number. (#107)
```
and
```
* commit 506422e110c58d6dd3cb8c9f8818dc22311ac8e1 (tag: v0.8.3)
| Author: Justin Boswell <boswej@amazon.com>
| Date:   Fri Apr 3 18:03:43 2020 -0700
|
|     Updated to v0.4.35 of aws-c-io to get windows TLS fix (#109)
```
but they are currently:
```
* commit 98ae7af4ffc7731643dc973e8ea1603c6395d45d (HEAD -> master, origin/master, origin/HEAD)
| Author: Dengke Tang <815825145@qq.com>
| Date:   Wed Jul 1 15:59:24 2020 -0700
|
|     update submodules (#142)
|
|     update submodules
|
| * commit 46b6bb9310f6c1956381435724122e3fbb3bdc14 (tag: v0.8.2)
| | Author: GitHub Actions <aws-sdk-common-runtime@amazon.com>
| | Date:   Tue Jun 30 21:33:27 2020 +0000
| |
| |     Updated version to v0.8.2
| |
| *   commit f4bca26f121f31fe69b06f1668506b44d3fe61cc (origin/multiple_sub)
| |\  Merge: a266c9c 8a454a2
| |/  Author: Dengke Tang <dengket@amazon.com>
|/|   Date:   Tue Jun 30 14:32:24 2020 -0700
| |
| |       Merge branch 'master' of https://github.com/awslabs/aws-crt-cpp
| |
```
and
```
* commit f3663653a5a0db531d16348a5a825202c951e98a (tag: v0.8.3)
| Author: GitHub Actions <aws-sdk-common-runtime@amazon.com>
| Date:   Fri Jun 26 17:11:17 2020 +0000
|
|     Updated version to v0.8.3
|
* commit 59bef2b5cf3ff5e7c5136be738054e89e121ab67
| Author: Andrew Tang <tangliang551@gmail.com>
| Date:   Fri Jun 26 10:10:38 2020 -0700
|
|     Update license to remove Copyright year.
|
```

There is also version v0.10.0, which seems surprising:

```
| * commit 6ca06bd95f91de9f7c0b35c7fd82050a7ec99147 (tag: v0.10.0)
|/  Author: GitHub Actions <aws-sdk-common-runtime@amazon.com>
|   Date:   Wed Jun 17 23:20:38 2020 +0000
|
|       Updated version to v0.10.0
|
* commit 9fda1e3309a4de37c2f052c5b1d531537c70b8a3
| Author: Justin Boswell <boswej@amazon.com>
| Date:   Wed Jun 17 16:19:46 2020 -0700
|
|     Try normal force (#139)
|
```

**Comment by justinboswell** [comment]
This was during fixup of our automation for versioning. The current version is correct, v0.8.6. You will note that the versions you are referring to are not in releases, this is intentional. 

Prior versions had not baked in the correct library version since v0.8.2 IIRC. Other than that, the main difference is bug fixes. The re-assignment of tags was due to an incorrect mismatch of release vs embedded version, and the v0.10.0 tag was for testing, that one I can actually delete. Either way, the version changes are inconsequential functionally.

**Comment by kankri** [comment]
> You will note that the versions you are referring to are not in releases, this is intentional.

I'm not sure what you mean by that. I can see e.g.  v0.8.2 in https://github.com/awslabs/aws-crt-cpp/releases and if I click that tag, it leads https://github.com/awslabs/aws-crt-cpp/tree/v0.8.2 which doesn't show the content of that release as it was on March 27.

> Prior versions had not baked in the correct library version since v0.8.2 IIRC.

The versions since v0.3.1 had wrong version numbers baked into the CMakeLists.txt, but I don't see how that is related to breaking existing tags. By all means make the baked in version number match with the Git tag in the future, but there is no need to touch the previous baked in versions or previous tags.

> Either way, the version changes are inconsequential functionally.

I don't have an idea what this means, but just as an example, if I now clone tag v0.8.3 it doesn't build with my code, because the API has changed to what it was in the real v0.8.3. I don't consider that inconsequential.

Why is it so difficult to restore the tags?

**Comment by justinboswell** [comment]
After taking another look, @TingDaoK and I found that there is actually an automation issue, it looks like we used the wrong GitHub automation event to do tagging. I'm looking into solutions to this. In the meantime, please use v0.8.6, which is tagged correctly.

**Comment by kankri** [comment]
5 days ago also tag for [v0.8.1](../tree/v0.8.1) got broken. It was previously

```
* commit 4f2eb5dce4c2a115e7bbc4733597e3841aa5710d (tag: v0.8.1)
| Author: Jonathan M. Henson <henso@amazon.com>
| Date:   Thu Mar 26 20:20:31 2020 -0700
|
|     Update to use stream activiation refactor in aws-c-http. (#104)
|
|     * Update to use stream activiation refactor in aws-c-http.
|     * Updated default args for allocators to use the configured one. Updated STL allocator to allow PMR style allocators where it makes sense. Updated http to use the new stream activate() apis. Added test for stream that isn't activated.
|     * Updated to latest http version, updated api contract and documentation to reflect.
|     * Update to latest version of all crt libs.
```

and is now

```
* commit a5825623c1b3dc5b99c847e2baba804b66302150 (tag: v0.8.1)
| Author: GitHub Actions <aws-sdk-common-runtime@amazon.com>
| Date:   Wed Jul 8 16:17:56 2020 +0000
|
|     Updated version to v0.8.1
|
* commit 58e9121780c748f5e8068a260be3464140800b87
| Author: Bret Ambrose <bretambrose@gmail.com>
| Date:   Wed Jul 8 09:17:26 2020 -0700
|
|     Update io, http, auth to pull in various fixes
```

Here's the new commits that tag contains:

```
a582562 (tag: v0.8.1) Updated version to v0.8.1
58e9121 Update io, http, auth to pull in various fixes
98ae7af (HEAD -> master) update submodules (#142)
8a454a2 Update license to remove Copyright year. (#145)
fb751d0 Added jobs for compiling against all supported C++ standards (#140)
9fda1e3 Try normal force (#139)
ef81c01 Fixed sed regex (#138)
241b615 Fixing automated push (#137)
a319dc4 Fixed checkout config (#136)
fefc477 Pass github token to update script (#135)
a13da01 Fixed push remote in update script (#134)
225387e Added git config (#133)
239a18f Fixed version update action (#132)
1d47f48 Fixed git diff check in release action (#131)
5c075b6 Fixed version update (#130)
212e32c Removed filtering on when release job runs (#129)
a920d40 Added a job that updates version in CMakeLists.txt when a new tag is created (#128)
673423e Use git tag for version (#127)
c1a7222 Fixed inverted logic in base64 encode/decode (#126)
2e9625f s2n -> f08b704 (Apr 9 2020) (#125)
393433e (orig tag: v0.8.5) Auth API update (#115)
c524d3a Added job for Windows+VS14 (#123)
421a69a (orig tag: v0.8.4) Update to get static CRT support from aws-c-common, doc update (#121)
6119e7e Support STATIC_CRT setting like aws-c-* libraries do (#117)
915b6cd Exposing functionality to set minimum TLS version (#119)
4a0a093 Updating aws-c-* dependencies (#120)
2e3ae39 UUID ToString & test (#118)
01cb75e Docs(phase 1) (#114)
f066bc2 Elasticurl (#111)
89917f8 Re-enable tests in CI (#113)
9046dd5 Bootstrap shutdown (#112)
506422e (orig tag: v0.8.3) Updated to v0.4.35 of aws-c-io to get windows TLS fix (#109)
1549aaf Android support (#108)
e84c340 (orig tag: v0.8.2) Forgot to update the version number. (#107)
4f2eb5d (orig tag: v0.8.1) Update to use stream activiation refactor in aws-c-http. (#104)
```

**Comment by justinboswell** [comment]
Ok, finally figured this out, thanks for the report! Turns out, it's a little weird to update a file as part of doing a release for GitHub. 

v0.8.7 has been released. We'll look into restoring the old tags, but it's going to be tough since they were force pushed.

**Comment by kankri** [comment]
I noticed also version tags v0.7.4, v0.7.5 and v0.7.6 got broken since I last checked!

Is there a reason you can’t do the following commands?
 
```
git tag -f v0.7.4 cec5295673483a4c0e8ea25da4304291ad101db6
git tag -f v0.7.5 2060ca18bb95e36b1b695498efd2221e8b2d9cfe
git tag -f v0.7.6 7d3c0b40d83a9d7a22821b302947b0fba3f4be01
git tag -f v0.8.1 4f2eb5dce4c2a115e7bbc4733597e3841aa5710d
git tag -f v0.8.2 e84c3402ee0a1d00d5d66a0a8e803f33a64fccb4
git tag -f v0.8.3 506422e110c58d6dd3cb8c9f8818dc22311ac8e1
git tag -f v0.8.4 421a69a81fb73b4c9917ffb3d095c2c65e9e973d
git tag -f v0.8.5 393433e9fcfe48ab09c02a23577724f96dcdee5f
git push --force --tags git@github.com:awslabs/aws-crt-cpp.git
```

**Comment by TingDaoK** [comment]
We apologize that the old tags were messed up. It's not easy to figure out where they were pointing at. The tags are restored now. Thank you so much for your help!
