### ISSUE TITLE
Crash in TlsContext::NewConnectionOptions() due to dereferencing a null pointer

### ISSUE THREAD

**Issue by EeroKurimo** [awslabs/aws-crt-cpp#177]
We've observed in some cases the underlying ``std::shared_ptr<aws_tls_ctx> m_ctx`` member of ``TlsContext`` may be storing a ``null`` when ``TlsContext::NewConnectionOptions()`` is called by ``MqttClient::NewConnection()``, which will cause the application crash. If in https://github.com/awslabs/aws-crt-cpp/blob/bd28bc4075d936c6fc49e60a8438dd25c1decead/source/io/TlsOptions.cpp#L286 the member variable ``m_ctx`` is storing null pointer, accessing ``m_ctx->alloc`` will crash in most compilers.

**Comment by rccarper** [comment]
Hello, sorry that you're running into this.  I see a possible way this might happen, and am still investigating the best way to prevent a resulting crash.  Is it possible that you are sometimes passing a TlsContext that's not initialized to MqttClient::NewConnection?  (ie: the TlsContext was either created using the constructor with zero arguments, or copied from another TlsContext that was created in that way.)  Also, would it be possible to provide a callstack for the crash?  A log may be helpful as well.

**Comment by EeroKurimo** [comment]
I found this while investigating another issue I opened in https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/162. Unfortunately I don't have access to work environment now so I can't get you a full backtrace until tomorrow, but in the one repro I saw this we were calling ``NewConnection(..., Io::TlsContext(tls_ctx_opt, Io::TlsMode::CLIENT))`` of https://github.com/awslabs/aws-crt-cpp/blob/f94efb11079eec6cf234d17430eafdb291930201/source/mqtt/MqttClient.cpp#L690 but the ``TlsContext`` ends up failing to initializing ``m_ctx`` when it tries to import the private key into the system in https://github.com/awslabs/aws-c-io/blob/2862e9ca07f5475b5490e645aec37ead8120ad96/source/darwin/darwin_pki_utils.c#L71.

I think the example code https://github.com/aws/aws-iot-device-sdk-cpp-v2/blob/b7a5dd3eb7d89d799c5928d9c041696a7850a3a9/samples/mqtt/basic_pub_sub/main.cpp#L399 should also fail in similar manner, as the config builder https://github.com/awslabs/aws-crt-cpp/blob/628fd48b5d32ca9a627bcf92c5d15a7eced7fbaf/source/iot/MqttClient.cpp#L272 similarly doesn't check if the TlsContext was constructed into working state.

However, as you also mentioned, it's easy imagine a lot more ways to end up with an empty ``TlsContext::m_ctx`` from all kinds of platform specific errors happening during the TlsContext constructor call to ``aws_tls_client_ctx_new``, which is why I though that a separate issue should be created for this null pointer dereferencing issue.

**Comment by rccarper** [comment]
Thank you for the additional information!  Just to give you a quick update: I'm still looking into the other issue that you posted, but for the crash in this ticket, we have a fix in review (shown above) to prevent it.

**Comment by rccarper** [comment]
The fix mentioned previously is now in release v0.10.6.  The fix prevents the TlsContext::NewConnectionOptions crash, and will also prevent MqttClient::NewConnection from trying to use an invalid TlsContext.  If you see this issue again, just let us know.
