### ISSUE TITLE
TLS negotiation error using 

### ISSUE THREAD

**Issue by Kevin-Tacheny** [awslabs/aws-crt-cpp#19]
Using Ubuntu16 (x64) and raspberry pi:
connection_manager branch fails tls negotiation with greengrass core on a cisco RV110W router.

**Comment by JonathanHenson** [comment]
Any chance you could get me a tcpdump?

**Comment by Kevin-Tacheny** [comment]
I will try to find some time once I finish some lambda work

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
