### ISSUE TITLE
Support custom keychain on macOS

### ISSUE THREAD

**Issue by EeroKurimo** [awslabs/aws-crt-cpp#204]
In aws/aws-iot-device-sdk-cpp-v2#163 I suggested adding support for using a custom keychain instead of the default login keychain for use-cases like daemons using the AWS IoT SDK. It was suggested that I'd instead change the default keychain for the account to the private keychain, or just a PKCS#12 file which appeared to not use a keychain.

As commented in the ticket, now when doing the daemon integration, we wound that changing the default keychain of the daemon account appeared to cause some other issues, and using PKCS#12 appears to also rely on the default keychain. To avoid dealing with the default keychain, I'd wish to add support for optionally using a custom private keychain for the IoT TLS connections only.

This issue covers the changes for aws-crt-cpp to support the changes in https://github.com/awslabs/aws-c-io/issues/340

**Comment by EeroKurimo** [comment]
This pull request can be ignored until https://github.com/awslabs/aws-c-io/pull/341 is wrapped up, as any changes there may need to be reflected here.

**Comment by bretambrose** [comment]
Previously merged.
