### ISSUE TITLE
Access violation in TlsConnectionOptions member functions

### ISSUE THREAD

**Issue by EeroKurimo** [awslabs/aws-crt-cpp#223]
Our code looks like this:
```
tls_ctx_opt = Io::TlsContextOptions::InitClientWithMtls(
	ByteCursorFromCString(cert),
	ByteCursorFromCString(key));
Io::TlsContext tls_ctx{tls_ctx_opt, Io::TlsMode::CLIENT};
Io::TlsConnectionOptions tls_opt = tls_ctx.NewConnectionOptions();
auto cur = ByteCursorFromCString(conn_opt.HostName.c_str());
tls_opt.SetServerName(cur);
```
If the `tls_ctx` constructor fails, the call `tls_opt.SetServerName()` causes an access violation for accessing the uninitialized member `Io::TlsConnectionOptions::m_allocator`.

What appears to happen is that when we call `tls_ctx.NewConnectionOptions()`, the function `isValid()` will be `false`, so we get an empty `TlsConnectionOptions()` object:
```
TlsConnectionOptions TlsContext::NewConnectionOptions() const noexcept
{
  if (!isValid())
  {
    AWS_LOGF_ERROR(
      AWS_LS_IO_TLS, "Trying to call TlsContext::NewConnectionOptions from an invalid TlsContext.");
    return TlsConnectionOptions();
  }
  return TlsConnectionOptions(m_ctx.get(), m_ctx->alloc);
}
```

This allocates the `tls_opt` into state where its `m_isInit=false`, `m_lastError=AWS_ERROR_SUCCESS` and `m_allocator=<uninitialized random value>`. When we then call `tls_opt.SetServerName()`, it gives the invalid `m_allocator` pointer to `aws_tls_connection_options_set_server_name`, which dereferences it.

**Comment by bretambrose** [comment]
I think this has been addressed by previous PRs now.
