### ISSUE TITLE
Mqtt::ReturnCode Bug in sample

### ISSUE THREAD

**Issue by ravichandhraRean** [awslabs/aws-crt-cpp#27]
Hi @graebm / @JonathanHenson ,

the recent updates,
1. The Mqtt::ConnectionState enum has been removed from the latest version of the SDK
2. Introduced Mqtt::ReturnCode

If you look into this sample code both,
1. In onConnectionCompleted callback lambda it is treating if there is no errorCode means connection is successful and just printing the connection completed message with  returnCode
2. In onResumed callback lambda it is not even checking the returnCode and just printing the message
3. In both cases it is assuming that the returnCode is always gives succes but If we look into the mqtt.h file there is a possibility of getting returnCode with different errors(We tested it we got 4/5 sometimes)
4. Our further business logic depends on this initial mqtt connection status and connection resume status, So could you please look into this.

```
/* Result of a connect request [MQTT-3.2.2.3]. */
enum aws_mqtt_connect_return_code {
    AWS_MQTT_CONNECT_ACCEPTED,
    AWS_MQTT_CONNECT_UNACCEPTABLE_PROTOCOL_VERSION,
    AWS_MQTT_CONNECT_IDENTIFIER_REJECTED,
    AWS_MQTT_CONNECT_SERVER_UNAVAILABLE,
    AWS_MQTT_CONNECT_BAD_USERNAME_OR_PASSWORD,
    AWS_MQTT_CONNECT_NOT_AUTHORIZED,
    /* reserved = 6 - 255 */
};
```

```
    /*
     * This will execute when an mqtt connect has completed or failed.
     */
    auto onConnectionCompleted = [&](Mqtt::MqttConnection &, int errorCode, Mqtt::ReturnCode returnCode, bool) {
        if (errorCode)
        {
            fprintf(stdout, "Connection failed with error %s\n", ErrorDebugString(errorCode));
            std::lock_guard<std::mutex> lockGuard(mutex);
            connectionSucceeded = false;
        }
        else
        {
            fprintf(stdout, "Connection completed with return code %d\n", returnCode);
            connectionSucceeded = true;
        }
        {
            std::lock_guard<std::mutex> lockGuard(mutex);
            connectionCompleted = true;
        }
        conditionVariable.notify_one();
    };
```

`auto onResumed = [&](Mqtt::MqttConnection &, Mqtt::ReturnCode, bool) { fprintf(stdout, "Connection resumed\n"); };`

Thank you.

Regards,
Ravichandhra Palla.

**Comment by ColdenCullen** [comment]
Hi, are you requesting that we printf something different in the onResumed callback? Or is there more here that I'm missing?

**Comment by ravichandhraRean** [comment]
Hi @ColdenCullen ,

1. on both onConnectionCompleted , onResumed  we should check the value of Mqtt::ReturnCode because there is possibility of getting any one from this enum (while one of our tests we got 4 and 5 for Mqtt::ReturnCode)

```
/* Result of a connect request [MQTT-3.2.2.3]. */
enum aws_mqtt_connect_return_code {
    AWS_MQTT_CONNECT_ACCEPTED,
    AWS_MQTT_CONNECT_UNACCEPTABLE_PROTOCOL_VERSION,
    AWS_MQTT_CONNECT_IDENTIFIER_REJECTED,
    AWS_MQTT_CONNECT_SERVER_UNAVAILABLE,
    AWS_MQTT_CONNECT_BAD_USERNAME_OR_PASSWORD,
    AWS_MQTT_CONNECT_NOT_AUTHORIZED,
    /* reserved = 6 - 255 */
};
```

Thank you.

Regards,
Ravichandhra Palla.

**Comment by ColdenCullen** [comment]
You are absolutely correct. Are you just asking that we add this check to the sample?

**Comment by ravichandhraRean** [comment]
Hi @ColdenCullen ,

1. this is fine, we are building a production ready device_agent using this sdk so just understanding the sdk and making sure it's behavior
2. It would really help us if we have any kind of documentation to use this sdk properly

Final I found one more bug in MQTT Connection, I will raise another issue for it but before that,
1. Is it possible for you to send me this MQTT Connection behavior with both IoT Core and Greengrass

Thank you.

Regards,
Ravichandhra Palla,
ravichandhra.palla@hitachivantara.com

**Comment by ColdenCullen** [comment]
Ok I think I understand the issue now. If either `return_code` OR `error_code` is non-zero, then the connection has failed, and is not open. This is true for both IoT Core and Greengrass without you needing to do anything special.

**Comment by ravichandhraRean** [comment]
Yes @ColdenCullen you are right and I got it. I just raised this issue to get a confirmation from you because samples are not good to understand this and no docs. I am closing this now and I will open another issue which is critical for us please help us to close that.

Thank you.
