### ISSUE TITLE
aws-c-common latest code not being pulled

### ISSUE THREAD

**Issue by amitguptaRean** [awslabs/aws-crt-cpp#32]
https://github.com/awslabs/aws-crt-cpp/blob/8d403e23fcc279fd0a7c8f96e8fe079717827598/aws-common-runtime/CMakeLists.txt#L20

@JonathanHenson  change "v0.3.14" to "master" so as the build can take latest changes that came to master branch in aws-c-common

**Comment by ravichandhraRean** [comment]
@amitguptaRean we can close this issue, now v0.3.15 tag contains the updates.

Thank you.
