### ISSUE TITLE
#if when #ifdef should be used - inconsistent with AWS SDK C++

### ISSUE THREAD

**Issue by M-Pixel** [awslabs/aws-crt-cpp#330]
The include headers contain a mix of `#if _MSC_VER` and `#ifdef _MSC_VER`.  When compiled with strict warning-as-error settings, this produces the error `'_MSC_VER' is not defined, evaluates to 0`.  The problem cannot be solved by defining `_MSC_VER=0` in the build system, because this would cause the `#ifdef` statements to produce false-positives.  The `#if`s should be replaced with `#ifdef`s.  This occurs with at least one other symbol in addition to `_MSC_VER`.

**Comment by jmklix** [comment]
Thanks for pointing this out. Looking into making these changes

**Comment by jmklix** [comment]
All of the changes have been merged. Please allow for a few days before all of the dependencies are updated. Or you can manually update them yourself if you would like to test the changes now.

**Comment by graebm** [comment]
[aws-crt-cpp v0.19.8](https://github.com/awslabs/aws-crt-cpp/releases/tag/v0.19.8) contains all fixes

**Comment by JBakamovic** [comment]
@graebm Unfortunately the same happens with a few other symbols and which makes it incredibly easy to miss the actual important warnings because the build output is quite bloated with these warnings.

Could you please address the following symbols as well, please?

- `__clang_analyzer__`
- `__APPLE__`
- `__linux__`
- `AWS_DEEP_CHECKS`

**Comment by graebm** [comment]
what compiler version, and what warning level are you setting?

Are you setting this warning level on your application? Or are you setting it globally via CFLAGS?

**Comment by graebm** [comment]
Ah, you're using MSVC
You can disable warnings from external headers via:
https://learn.microsoft.com/en-us/cpp/build/reference/external-external-headers-diagnostics

**Comment by JBakamovic** [comment]
The warning level is set on the application level - through cmake. The code is built with GCC (11.1.0, 12.1.0), clang (14.0.5, 15.0.6) and MSVC (19.32) and described issues persist on all of those compilers.

**Comment by jmklix** [comment]
This was fixed with the above pr. Please let us know if you notice any other inconsistencies with these repo's
