### ISSUE TITLE
aws-c-io tests fail to link for gcc-linaro-6.3.1 x86-64 arm-linux toolchain

### ISSUE THREAD

**Issue by david-haim-silo** [awslabs/aws-crt-cpp#38]
Hi there guys.

We're using the MQTT client in our IOT product that runs on a specific hardware.
After I managed to build this project as a stand alone library on my development machine for  x86-64 Intel CPU, I tried to compile this project using our IOT toolchain (gcc-linaro-6.3.1 x86_64_arm-linux)

s2n project fails to be compiled with the error message

```
[100%] Linking C executable aws-c-io-tests
/connector-build-deps/lib/libs2n.a(s2n_random.c.o): In function `s2n_rand_init':
s2n_random.c:(.text+0x1b8): undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
tests/CMakeFiles/aws-c-io-tests.dir/build.make:618: recipe for target 'tests/aws-c-io-tests' failed
make[5]: *** [tests/aws-c-io-tests] Error 1
CMakeFiles/Makefile2:1018: recipe for target 'tests/CMakeFiles/aws-c-io-tests.dir/all' failed
make[4]: *** [tests/CMakeFiles/aws-c-io-tests.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/AwsCIO.dir/build.make:111: recipe for target 'build/src/AwsCIO-stamp/AwsCIO-build' failed
make[2]: *** [build/src/AwsCIO-stamp/AwsCIO-build] Error 2
CMakeFiles/Makefile2:179: recipe for target 'CMakeFiles/AwsCIO.dir/all' failed
make[1]: *** [CMakeFiles/AwsCIO.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
CMake Error at CMakeLists.txt:80 (message):
  Failed to build aws crt libraries.


```

**Comment by bretambrose** [comment]
This isn't the s2n build, it's aws-c-io-tests  linking in s2n.  

Can you post the full cmake output of your build?

Also, can you locate and paste the contents of the link.txt generated cmake file for aws-c-io-tests?  It will be under your build directory in a path somewhat similar to  "..../tests/CMakeFiles/aws-c-io-tests.dir/link.txt". 

For example, my local version looks like:

```
/usr/bin/cc -g  -rdynamic CMakeFiles/aws-c-io-tests.dir/test_runner.c.o CMakeFiles/aws-c-io-tests.dir/alpn_handler_test.c.o CMakeFiles/aws-c-io-te
sts.dir/channel_test.c.o CMakeFiles/aws-c-io-tests.dir/default_host_resolver_test.c.o CMakeFiles/aws-c-io-tests.dir/event_loop_test.c.o CMakeFiles
/aws-c-io-tests.dir/file_utils_test.c.o CMakeFiles/aws-c-io-tests.dir/io_testing_channel_test.c.o CMakeFiles/aws-c-io-tests.dir/logging/log_channe
l_test.c.o CMakeFiles/aws-c-io-tests.dir/logging/log_formatter_test.c.o CMakeFiles/aws-c-io-tests.dir/logging/log_writer_test.c.o CMakeFiles/aws-c
-io-tests.dir/logging/pipeline_logger_test.c.o CMakeFiles/aws-c-io-tests.dir/mock_dns_resolver.c.o CMakeFiles/aws-c-io-tests.dir/pipe_test.c.o CMa
keFiles/aws-c-io-tests.dir/pki_utils_test.c.o CMakeFiles/aws-c-io-tests.dir/read_write_test_handler.c.o CMakeFiles/aws-c-io-tests.dir/shared_libra
ry_test.c.o CMakeFiles/aws-c-io-tests.dir/socket_handler_test.c.o CMakeFiles/aws-c-io-tests.dir/socket_test.c.o CMakeFiles/aws-c-io-tests.dir/stre
am_test.c.o CMakeFiles/aws-c-io-tests.dir/tls_handler_test.c.o CMakeFiles/aws-c-io-tests.dir/uri_test.c.o  -o aws-c-io-tests -Wl,-rpath,/home/loca
l/ANT/bambrose/projects/crt/aws-c-io/_build:/home/local/ANT/bambrose/projects/crt/install/lib ../libaws-c-io.so.1.0.0 /home/local/ANT/bambrose/pro
jects/crt/install/lib/libaws-c-common.so.1.0.0 -pthread /home/local/ANT/bambrose/projects/crt/install/lib/libs2n.a -lpthread /usr/lib/x86_64-linux
-gnu/libcrypto.so -ldl -lm -lrt
```

In particular, you can see that `-lpthread` comes after `libs2n.a` which is the order it needs to be in in order to link properly.

**Comment by david-haim-silo** [comment]
Hi there
sorry for the late response, we've been overhauling our build system from a-z, and this is part of it :)
[toolchain_error.txt](https://github.com/awslabs/aws-crt-cpp/files/3382698/toolchain_error.txt)
[link.txt](https://github.com/awslabs/aws-crt-cpp/files/3382712/link.txt)

anyway, those are the files you requested

**Comment by david-haim-silo** [comment]
Hi there, any new regarding this?

**Comment by justinboswell** [comment]
I see the problem in link.txt: the ```-lpthread``` should come after libcrypto, which indicates that libcrypto as we're importing it doesn't declare its dependency on pthreads. Let me mess with the configuration a bit and see if we can fix this upstream.

**Comment by justinboswell** [comment]
As we don't have access to a Linaro gcc ARM machine at the moment, could you give [this branch](https://github.com/awslabs/aws-crt-cpp/tree/dependencies) a try? If that works for you, I'll push all the PRs through and make a new release.

**Comment by david-haim-silo** [comment]
It didn't :(
[link.txt](https://github.com/awslabs/aws-crt-cpp/files/3456696/link.txt)
[cmake_error.txt](https://github.com/awslabs/aws-crt-cpp/files/3456697/cmake_error.txt)

**Comment by justinboswell** [comment]
Ok, I'm looking into setting up a similar environment so I can test this. In the meantime, can you confirm that you can link a program using this toolchain which references pthread_atfork()?

Perhaps something like the following:
```cpp
#include <pthread.h>
#include <stdio.h>
#include <sys/types.h>
#include <unistd.h>

void s_atfork_parent(void) {
    printf("Hello from parent\n");
}

void s_atfork_child(void) {
    printf("Hello from child\n");
}

void s_atfork_prepare(void) {
    printf("GET READY\n");
}

int main(int argc, char **argv) {
    pthread_atfork(s_atfork_prepare, s_atfork_parent, s_atfork_child);

    pid_t pid = 0;
    switch (pid = fork()) {
        case 0:
            exit(0);
        case -1:
             printf("Failed to fork()\n");
            exit(-1);
        default:
            int status = 0;
            waitpid(pid, &status, 0);
            break;
    }
    return 0;
}
```

Try just adding -pthread at the end of the link line.

**Comment by david-haim-silo** [comment]
Hi there, and thank you very much!

to our suprise , the toolchain couldn't compile your code example, producing the same error (undefined reference to pthread_atfork). meaning that the problem is not necessarily in aws-c-io tests, but rather in the toolchain (which is not ours, anyway).

So, first of all thanks, and for now let's close it until out team realizes what to do with the toolchain.

again, thanks.
