### ISSUE TITLE
Memory leak at JsonObject::NewArray(Vector<JsonObject> &&objectsToMove)

### ISSUE THREAD

**Issue by mkaranki** [awslabs/aws-crt-cpp#505]
### Describe the bug

There is a memory leak at [JsonObject::NewArray(Vector<JsonObject> &&objectsToMove)](https://github.com/awslabs/aws-crt-cpp/blob/0e747152208198b56033339a9d6af4d541c74c0a/source/JsonObject.cpp#L191)

In the loop, objects are supposed to be moved. Nevertheless, there's a `aws_json_value_duplicate` call made for the object and then the old m_value is just assigned to nullptr (without calling `aws_json_value_destroy`). Seems like a copy paste error from the method above in the file?

### Expected Behavior

No object/memory leaks when C++ move semantics is used.

### Current Behavior

Consider a code:

```c++
JsonObject object;
...
object.WithArray("whatever", std::move(object_vector));
```

This calls  JsonObject::NewArray(Vector<JsonObject> &&objectsToMove), creating unnecessary copies of all the objects but forgetting to free the old ones.

### Reproduction Steps

If you need, I can provide full example, but this seems quite clear even without it?

### Possible Solution

It seems obvious that aws_json_value_duplicate should not be called with rvalue objectsToMove.

### aws-crt-cpp version used

main branch

### Compiler and version used

gcc

### Operating System and version

ubuntu linux

**Comment by graebm** [comment]
Fixed
Thanks for the great writeup!
