### ISSUE TITLE
CMake Error at CMakeLists.txt:317 (aws_add_sanitizers): Unknown CMake command "aws_add_sanitizers"

### ISSUE THREAD

**Issue by nunotexbsd** [awslabs/aws-crt-cpp#548]
### Describe the bug

Configure fails:

```
===>  Configuring for aws-crt-cpp-0.24.0
===>  Performing out-of-source build
/bin/mkdir -p /wrkdirs/usr/ports/devel/aws-crt-cpp/work/.build
-- AWS CRT C++ 0.24.0
-- The CXX compiler identification is Clang 14.0.5
-- The C compiler identification is Clang 14.0.5
<snip>
-- aws-c-cal found target: AWS::crypto
-- crypto Include Dir: /usr/include
-- aws-c-cal found target: AWS::crypto
-- crypto Include Dir: /usr/include
-- S2N found target: AWS::crypto
-- crypto Include Dir: /usr/include
-- S2N found target: AWS::crypto
-- crypto Include Dir: /usr/include
-- aws-c-cal found target: AWS::crypto
-- crypto Include Dir: /usr/include
CMake Error at CMakeLists.txt:317 (aws_add_sanitizers):
  Unknown CMake command "aws_add_sanitizers".


-- Configuring incomplete, errors occurred!
*** Error code 1
```
Configure fails: 

### Expected Behavior

configure ok

### Current Behavior

configure fails related to CMAkeLists: 317

`aws_add_sanitizers(${PROJECT_NAME})`

### Reproduction Steps

cmake

### aws-crt-cpp version used

0.24.0

### Compiler and version used

clang 14.0.5

### Operating System and version

FreeBSD 13.2 amd64

**Comment by nunotexbsd** [comment]
Hello @yasminetalby ,

Build is doing on FreeBSD ports framework ([aws-crt-cpp port](https://www.freshports.org/devel/aws-crt-cpp/))and it is a trivial update from 2.23.1 to 2.24.0:
https://people.freebsd.org/~eduardo/logs/aws-crt-cpp/aws-crt-cpp-0.24.0.log

It seems related to https://github.com/awslabs/aws-crt-cpp/commit/7c15c5b60b8d7578da2857e235684f478ad9a219 since previous builds are ok.

**Comment by nunotexbsd** [comment]
@yasminetalby

Comment aws_add_sanitizers fixes build:
 
```
--- CMakeLists.txt.orig 2023-10-04 19:28:22 UTC
+++ CMakeLists.txt
@@ -314,7 +314,7 @@ aws_use_package(aws-c-s3)
 aws_use_package(aws-c-event-stream)
 aws_use_package(aws-c-s3)

-aws_add_sanitizers(${PROJECT_NAME})
+#aws_add_sanitizers(${PROJECT_NAME})

 target_link_libraries(${PROJECT_NAME} PUBLIC ${DEP_AWS_LIBS})
```

https://people.freebsd.org/~eduardo/logs/aws-crt-cpp/aws-crt-cpp-0.24.0_HOTFIX.log

Hope that helps.
Thanks

**Comment by thomas-roos** [comment]
we (https://github.com/aws4embeddedlinux/meta-aws) can also confirm this issue

**Comment by xiazhvera** [comment]
Fixed in latest release: https://github.com/awslabs/aws-crt-cpp/releases/tag/v0.24.2

**Comment by nunotexbsd** [comment]
Thanks for fix!
