### ISSUE TITLE
CMake Deprecation Warnings

### ISSUE THREAD

**Issue by nabelekt** [awslabs/aws-crt-cpp#606]
### Describe the bug

I am using v0.26.4 and getting many warnings like this when building:
```
CMake Deprecation Warning at libraries/third_party/aws-crt-cpp/crt/aws-c-sdkutils/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
```
The fix is given the last two lines there.

### Expected Behavior

No warnings when building

### Current Behavior

See above

### Reproduction Steps

Build with the library

### aws-crt-cpp version used

0.26.4

### Compiler and version used

gcc version 13.2.0 (Ubuntu 13.2.0-4ubuntu3)

### Operating System and version

Ubuntu 23.10

**Comment by nabelekt** [comment]
For what it's worth, https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/setup-linux.html specifies the CMake minimum versions as 3.13.

**Comment by DmitriyMusatkin** [comment]
Note that CRT and SDK are separate projects, with CRT being a dependency of CPP SDK. And while CPP SDK has a min cmake version 3.13, CRT supports much older cmake versions. 

We do want to increase our min version in the future, but as of right now we dont have a concrete date on when that might happen

**Comment by graebm** [comment]
It's possible to shut these warnings up by stating that your project is known to be compatible with later versions, like:
`cmake_minimum_required(VERSION 3.1...3.29)`

unfortunately, this isn't supported until cmake 3.12, so the code would need to be like:
```
if (CMAKE_VERSION VERSION_LESS "3.12")
    cmake_minimum_required(VERSION 3.1)
else ()
    cmake_minimum_required(VERSION 3.1...3.29)
endif ()
```

**Comment by jmklix** [comment]
You should no longer see any deprecation warnings from any of the crt repositories. We have updated our [minimum cmake version to 3.9](https://github.com/awslabs/aws-crt-cpp/blob/main/CMakeLists.txt#L1). You might still see some other cmake warnings from other dependencies. One of them is s2n-tls. I opened an issue [here](https://github.com/aws/s2n-tls/issues/4899) asking them to fix it.
