### ISSUE TITLE
aws-crt-cpp-mqtt-pub-sub v0.5.5 hangs

### ISSUE THREAD

**Issue by dbmoderro** [awslabs/aws-crt-cpp#62]
Hi. How I compile it:

```
m -rf aws-crt-cpp
git clone --branch v0.5.5 https://github.com/awslabs/aws-crt-cpp.git

B="$PWD/B"
rm -rf "$B"

rm -rf aws-crt-cpp-build
mkdir aws-crt-cpp-build
cd aws-crt-cpp-build

cmake -DCMAKE_INSTALL_PREFIX="$B" -DCMAKE_PREFIX_PATH="$B" -DBUILD_SHARED_LIBS=ON -DBUILD_DEPS=ON ../aws-crt-cpp
cmake --build . --target install
```

Run:
```
./aws-crt-cpp-mqtt-pub-sub --endpoint "xxx.amazonaws.com" --cert "xxx" --key "xxx" --topic "xxx" --ca_file "xxx" --client_id "xxx"
```

Stdout:

> Connecting...
> Connection completed with return code 0
> Connection interrupted with error aws-c-common: AWS_ERROR_SUCCESS, Success.
> Connection resumed
> Connection interrupted with error aws-c-common: AWS_ERROR_SUCCESS, Success.
> Connection resumed
> Connection interrupted with error aws-c-common: AWS_ERROR_SUCCESS, Success.
> Connection resumed
> ...

It should ask to enter a text, but never does that. Because it has hanged in the subscription code here:

```
        // HANGS
        //
        conditionVariable.wait(uniqueLock);

        // NEVER EXECUTED
        while (true)
        {
            String input;
            fprintf(
                stdout,
                "Enter the message you want to publish to topic %s and press enter. Enter 'exit' to exit this "
```

FYI The Python sample (from here: https://github.com/aws/aws-iot-device-sdk-python) works fine with the same data/certs/keys/client-id/topic etc.

**Comment by dbmoderro** [comment]
Update: I'm sorry, the python sample doesn't work as well.

```
def customCallback():
    print("Subscribe msg")

awsMQTTClient.connect()
awsMQTTClient.publish(topic, message, 0)
awsMQTTClient.subscribe(topic, 1, customCallback)
awsMQTTClient.unsubscribe(topic)
```

> Subscribe timed out
> Traceback (most recent call last):
>   File "mqttclient.py", line 30, in <module>
>     awsMQTTClient.subscribe(topic, 1, customCallback)
>   File "/usr/local/lib/python3.6/dist-packages/AWSIoTPythonSDK/MQTTLib.py", line 696, in subscribe
>     return self._mqtt_core.subscribe(topic, QoS, callback)
>   File "/usr/local/lib/python3.6/dist-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 306, in subscribe
>     raise subscribeTimeoutException()
> AWSIoTPythonSDK.exception.AWSIoTExceptions.subscribeTimeoutException

Am I missing anything? Is there any specific configuration I need to apply to the MQTT broker in order to make subscriptions work?

**Comment by bretambrose** [comment]
It is very likely that something is wrong with your endpoint/cert/key/device policy document.  I was able to follow your build steps and connect fine.  Unfortunately, if everything is not "perfect" with your CONN message, the IoT service will just hang up on you with no reason given (it's optional in the MQTT spec).

I would check the policy document first and (temporarily) make it wide open to help narrow down the problem area.

That being said, we should update the sample to quit and print out a helpful message if the initial connect fails.

**Comment by dbmoderro** [comment]
Does subscribing require a direct connection from the mqtt broker to the client (who sends mqtt messages)? The mqtt broker is deployed in an Amazon EC2 instance which could block unwanted traffic. Could it be the root cause of the failure to subscribe?

P.S. Just to clarify once again: publishing mqtt nessages works just fine. Only subscription doesn't work.

**Comment by dbmoderro** [comment]
Is it OK if I provide my cert, key, and the broker address for further debugging on your side? If it works for you, I can send all the required data in a Skype message, for example.

**Comment by dbmoderro** [comment]
@bretambrose Yes, probably it's an AWS IoT service deployed in EC2. The service owner told me it's OK to provide the cert/key as they can easily replace it, and the service itself is in an alpha testing.

**Comment by bretambrose** [comment]
Are you still having trouble here?
