### ISSUE TITLE
cross compile for arm embedded linux

### ISSUE THREAD

**Issue by certabitmh** [awslabs/aws-crt-cpp#79]
Hi,
my environment:
- Ubuntu 16.04 VM
- emb. Linux cross compile toolchain with openssl + libcrypto libs available
- emb. Linux provides script which sets all paths to target compile toolchain, so one can use cmake / make and gcc,... for arm target is automatically set

when in the directory to build, I do:

> cmake -DBUILD_DEPS=ON ../.

but get
>   Target "LibCrypto::Crypto" not found.

when deps are going to be built

tried to alter CMakeLists.txt and add link_directories with paths to the emb.linux libs, no success

Any ideas highly appreciated ...

**Comment by JonathanHenson** [comment]
Have you tried adding your libcrypto install to CMAKE_PREFIX_PATH?

My recommendation is to go ahead and create your install directory. Install libcrypto or whatever there. Then point the crt cmake run to that CMAKE_PREFIX_PATH and CMAKE_INSTALL_PREFIX

**Comment by certabitmh** [comment]
what I did so far:

1. created install directory in aws-crt-cpp: `aws-crt-cpp/install`
2. created build directory in aws-crt-cpp: `aws-crt-cpp/build `
3. copied libcrypto.a and libcrypto.so to `install` (from `/opt/embLinToolchain/host/arm-buildroot-linux-gnueabi/sysroot/usr/lib`)
4. cd build
5. exectued cmake: `cmake -DCMAKE_INSTALL_PREFIX="../install" -DCMAKE_PREFIX_PATH="../install" -DBUILD_DEPS=OFF ../`

now I get:
```
CMake Error at CMakeLists.txt:104 (include):
  include could not find load file:

    AwsCFlags


CMake Error at CMakeLists.txt:105 (include):
  include could not find load file:

    AwsSharedLibSetup


CMake Error at CMakeLists.txt:225 (aws_prepare_symbol_visibility_args):
  Unknown CMake command "aws_prepare_symbol_visibility_args".

```
sorry, I'm not very familiar with cmake...

**Comment by JonathanHenson** [comment]
A couple notes, you want to configure your openssl build with the install directory you’ve generated. It needs header files too. Then just run make installsw in openssl build Dir.

You’ll want to keep BUILD_DEPS=ON

CMAKE_PREFIX_PATH and CMAKE_INSTALL_PREFIX need to be absolute paths.

**Comment by certabitmh** [comment]
I don't build openssl, it comes with the emb.linux distribution...

**Comment by certabitmh** [comment]
somehow managed it to build: copied libcrypto.a / .so and .so.1..0 to /install directory and set CMAKE_PREFIX_PATH and CMAKE_INSTALL_PREFIX to this directory (abs path).

But when I try to run the shadow sample on the target, I get:

> Client Configuration initialization failed with error aws-c-common: AWS_ERROR_FILE_INVALID_PATH, Invalid file path.

tried to run it with:
`./shadow-sync --endpoint MYENDPOINT.iot.eu-west-1.amazonaws.com --key "/data/private.pem" --cert "/data/certificate.pem" --t
hing_name "MY-SECRET-THINGNAME" --shadow_property testSDK`

Private Key and cert are definitely correct and located in provided paths, since I use the same files with SDK v1
