### ISSUE TITLE
mqtt sample: AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE

### ISSUE THREAD

**Issue by certabitmh** [awslabs/aws-crt-cpp#80]
Although I successfully managed to connect and publish to aws iot on desktop ubuntu, I fail doing the same on my embedded linux target (same cert / key files):

tried:

> aws-crt-cpp-mqtt-pub-sub --endpoint SECRET-ats.iot.eu-west-1.amazonaws.com --cert "/data/certificate.pem.crt" --key "/data/private.pem.key" --topic "testsdkv2"

get:

> Connection failed with error aws-c-io: AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE, TLS (SSL) negotiation failed

Is there an issue with finding the libcrypt or something?

I'm able to ping the iot endpoint, policy allows iot actions...

**Comment by JonathanHenson** [comment]
Have you tried specifying a ca file? It’s usually AmazonRootCA1

**Comment by JonathanHenson** [comment]
If you had a problem finding libcrypto the application would not load (also we default to static linking). More likely, libcrypto doesn’t know where to find the default trust store or the trust store is missing AmazonRootCA1, you can download the ca file and pass it as a command line arg.

**Comment by certabitmh** [comment]
thanks for the fast response, downloaded root ca file and passed it , but same result :-(

**Comment by certabitmh** [comment]
seems `s2n_x509_validator_validate_cert_chain() ` called in `s2n_server_cert_recv()` in `s2n_server_cert.c:41 `returns `S2N_ERR_CERT_UNTRUSTED`

**Comment by certabitmh** [comment]
ok, one step further by providing the correct rootCA (took legacy instead of AmazonRootCA1)

`aws-crt-cpp-mqtt-pub-sub --endpoint MYENDPOINT-ats.iot.eu-west-1.amazonaws.com --cert "/data/secret-certificate.pem.crt" --key "/data/secret-private.pem.key" --topic "testsdkv2" --ca_file "/data/AmazonRootCA1.pem"`

now returns

`Connection failed with error libaws-c-mqtt: AWS_ERROR_MQTT_UNEXPECTED_HANGUP, The connection was closed unexpectedly.`

**Comment by certabitmh** [comment]
works now, hat to add "iot::Connect" to my policy in aws. Maybe add this to instructions?

**Comment by JonathanHenson** [comment]
sure, will do.

**Comment by ndvbd** [comment]
I have the same problem. My python sdk works fine, and this cpp client with the same parameters doesn't work. Do they have different "resource" id in the policy?

**Comment by anubhavHOH** [comment]
The reason I found was the x509.pem that you downloaded from aws website is not part of the trusted security certificate chain of the OS (issue in Ubuntu 20.04 LTS, Pi 3  but not in P4 with Raspbian buster). I guess it varies from OS to OS on how root certificates are added to the chain of trust

In ubuntu Amazon_Root_CA_1.pem is already available in /etc/ssl/certs and part of ca-certificates.crt. Using it from there will work. One could also bring a root ca certificate by updating  ca-certificates.crt using the ubuntu utility update-ca-certificates - update /etc/ssl/certs and ca-certificates.crt

Once, you are able to do this, it is a smooth sail. Also remember to update parser.add_argument('--count', default=10, type=int, help="0") to parser.add_argument('--count', default=0, type=int, help="0") in aws-iot-device-sdk-python-v2/samples/pubsub.py  to have infinite emission of mqtt messages.
