### ISSUE TITLE
Presigned URL with MQTT client

### ISSUE THREAD

**Issue by MattCrist** [awslabs/aws-crt-cpp#97]
Hi,

I'm trying to create a mqtt connection using a presigned url return from a subscription query to AWS appsync.

When I try to connect I get the following error:
```aws-c-io: AWS_IO_DNS_INVALID_NAME, Host name was invalid for dns resolution.```

The presigned url looks like this:
``` wss://iotendpoint-ats.iot.us-west-2.amazonaws.com/mqtt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AAAAAAAAAAAA%2F20200203%2Fus-west-2%2Fiotdevicegateway%2Faws4_request&X-Amz-Date=20200203T190240Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=<signature>&X-Amz-Security-Token=<token>```

Simplified code:
```
Aws::Crt::Mqtt::MqttClient *mqttClient = new Aws::Crt::Mqtt::MqttClient(bootstrap);

std::shared_ptr<Aws::Crt::Mqtt::MqttConnection> mqttConnection = mqttClient->NewConnection(url.c_str(), 443, Aws::Crt::Io::SocketOptions(), true);
```

First, I'm wondering if I should be able to use a presigned url with the MqttClient in the Crt library?  If so, is there something here I'm doing wrong?

**Comment by JonathanHenson** [comment]
Currently, this isn't going to work as coded, BUT you can install a websocket intercept hook and then add the query params to the url (this is exactly how sigv4 over websockets works). In fact if you'd like you can just let us generate that url for you. All you need to have to do that is a valid credentials provider (if default works even better), and specify websockets via the Aws::Iot::MqttConnectionBuilder interface.

If you want to control it without letting the sdk generate the url for you, you can install your own websockets interceptor to add whatever you'd like to the url.

See the pubsub demo for a code sample

**Comment by MattCrist** [comment]
Thanks for your help, I added the query string to the path inside the websocket interceptor worked.

It might be good to consider supporting pre-signed url's in the sdk.  That would allow someone to quickly make a c++ AppSync client.
